---
name: AddonsManager
main: kim\present\addonsmanager\Loader
version: 1.0.0
api: [ 4.0.0 ]
author: PresentKim
description: Manager of Addons(ResourcePak and BehaviorPack)
mcpe-protocol: [ 465 ]
...
